name: Auto Tagging

on:
  push:
    branches:
      - main  # Adjust this if you use a different branch

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Tags
        run: git fetch --tags

      - name: Auto Increment Version and Tag
        run: |
          # Get the latest tag or default to v0.0.0
          LATEST_TAG=$(git tag -l | sort -V | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
            echo "No tags found. Starting with v0.0.1"
            NEW_TAG="v0.0.1"
          else
            echo "Latest Tag: $LATEST_TAG"
            # Extract version components (vX.Y.Z)
            MAJOR=$(echo $LATEST_TAG | cut -d. -f1 | sed 's/v//')
            MINOR=$(echo $LATEST_TAG | cut -d. -f2)
            PATCH=$(echo $LATEST_TAG | cut -d. -f3)
            
            # Increment patch version
            NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"
          fi
          
          echo "New Tag: $NEW_TAG"
          
          # Tagging and pushing the new version
          git tag $NEW_TAG
          git push origin $NEW_TAG
